main.py
measurements/get_metrics.py
methods/tsetlin_machine.py
poetry.lock
predictions/HoltWinters.py
predictions/tsetlin_machine.py

Change Tsetlin implemention to include a grid search, splitting first into train, validation and test sets.

Add grid search to tsetlin machine

---

main.py
predictions/prophet.py

Adjust grid search to use validation for prophet

---

Makefile
poetry.lock

update to make file for prophet

---

data/impute_data.py
main.py
methods/comparison_plot_multi.py
plots/comparison_plot.py
plots/comparison_plot_multi.py
poetry.lock
predictions/AR.py
predictions/ARIMA.py
predictions/FCNN.py
predictions/FCNN_embedding.py
predictions/HoltWinters.py
predictions/MA.py
predictions/Prediction.py
predictions/SARIMA.py
predictions/SES.py
predictions/kalman_filter.py
predictions/linear_regression.py
predictions/prophet.py
predictions/tsetlin_machine.py

Multiple results on one plot per dataset/subset

---

main.py
plots/comparison_plot.py
predictions/AR.py
predictions/ARIMA.py
predictions/HoltWinters.py
predictions/MA.py
predictions/SARIMA.py
predictions/prophet.py

Applied to all methods except SES; grid search is currently not implemented for this method.
HoltWinters is implemented using MAPE, as BIC was not available on that model library.

Switch grid search to bic universally and grid search on whole training set

---

main.py
methods/tsetlin_machine.py
plots/comparison_plot.py
predictions/tsetlin_machine.py

Late addition to include Tsetlin machine

Correct grid search on Tsetlin to use full train

---

main.py
plots/comparison_plot.py
plots/plot_results_in_heatmap.py

Add ground truth to comparison plot

---

data/stock_prices.py
main.py
poetry.lock
pyproject.toml

Fix error with stock data

---

predictions/SES.py

Changed seasonality to True for stock price data! 
Fixes #65

Fix lack of seasonality in out of sample SES

---

predictions/prophet.py

A small fix after the merge of #77 and #76.
Fixes #75

Fix to add ds column for Prophet

---

main.py
poetry.lock
pyproject.toml

Small changes to dependencies (Python 3.10 enforce) and main.py (for multiple Indian city run)

Plotting multi on air travel test

---

main.py
plots/plot_results_in_heatmap.py

Heatmap w/o cities w/ small R2,reversed R2 clbar

---

measurements/get_metrics.py
measurements/store_metrics.py
methods/plot_results_in_heatmap.py

Add mape method

---

main.py
predictions/HoltWinters.py

Now given more margin for minimum number of data points

Fix holt winters crash on kolkata

---

data/list_of_tuples.py
main.py
methods/prophet.py
predictions/prophet.py

Fix prophet error on straight line

---

data/ecmwf_weather_data.py
data/impute_data.py
main.py
poetry.lock
predictions/ARIMA.py
predictions/SES.py
predictions/prophet.py
predictions/tsetlin_machine.py
pyproject.toml

Added holiday functionality to Prophet, currently mainly useful for Indian pollution data, but could be modified for stock data (with e.g. US holidays).

Prophet addition of holidays

---

plots/plot_results_in_heatmap.py
predictions/prophet.py

Change of the colorbar scale/abbrev for Hyderabad

---

main.py
plots/plot_results_in_heatmap.py

Changing the plotting method for heatmaps to be a clustered version

Change heatmap to sns clustermap

---

main.py
predictions/HoltWinters.py

Adjust datatype for NumPy array

---

data/impute_data.py
data/india_pollution.py
plots/plot_results_in_heatmap.py

Indian clustermap fix

---

.gitignore
data/report.py
main.py
measurements/store_metrics.py
methods/store_metrics.py

Report saving features

---

.gitignore
data/impute_data.py
data/india_pollution.py
main.py
predictions/SARIMA.py
predictions/auto_arima.py

Fixes #86 
Switching to parallel processing and error suppression

Fix sarima forecasts

---

main.py
plots/plot_results_in_heatmap.py

Fix missing title from clustermap

---

predictions/SARIMA.py

Further to #123 this adds a progressbar for parallel processing of SARIMA jobs

Progress bar for parallel working

---

data/stock_prices.py
main.py

This adds a couple of functions that create lists of stocks (two types, value and growth stocks) for the creation of stock price vs method clustermaps.

Multi stock run

---

main.py
plots/comparison_plot_multi.py

Fix to ylim pollution plots

---

data/india_pollution.py
plots/plot_results_in_scatter_plot.py

Minor fix to Indian coastal and inland cites' lists

Fix to indian cities list

---

main_plot.py
methods/plot_results_in_box_plot.py
methods/plot_results_in_heatmap.py
plots/comparison_plot.py
plots/plot_results_in_box_plot.py

A minor issue still remains unsolved here --> axis.fill_between doesn't work correctly when put together with pandas.plot(). Looks like an issue with data formatting.

Add comparison_plot into main_plot
